insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Albany","Animal","Amphibians","Frogs and Toads","Anaxyrus americanus","American Toad");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Albany","Animal","Amphibians","Frogs and Toads","Anaxyrus fowleri","Fowler's Toad");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Albany","Animal","Amphibians","Frogs and Toads","Hyla versicolor","Gray Treefrog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Albany","Animal","Amphibians","Frogs and Toads","Lithobates catesbeianus","Bullfrog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Albany","Animal","Amphibians","Frogs and Toads","Lithobates clamitans","Green Frog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Allegany","Animal","Amphibians","Frogs and Toads","Anaxyrus americanus","American Toad");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Allegany","Animal","Amphibians","Frogs and Toads","Anaxyrus fowleri","Fowler's Toad");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Allegany","Animal","Amphibians","Frogs and Toads","Hyla versicolor","Gray Treefrog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Allegany","Animal","Amphibians","Frogs and Toads","Lithobates catesbeianus","Bullfrog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Allegany","Animal","Amphibians","Frogs and Toads","Lithobates clamitans","Green Frog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Bronx","Plant","Flowering Plants","Other Flowering Plants","Crotalaria sagittalis","Rattlebox");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Bronx","Plant","Flowering Plants","Other Flowering Plants","Cuscuta pentagona","Five-angled Dodder");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Bronx","Plant","Flowering Plants","Other Flowering Plants","Desmodium ciliare","Little-leaf Tick Trefoil");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Bronx","Plant","Flowering Plants","Other Flowering Plants","Desmodium laevigatum","Smooth Tick Trefoil");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Bronx","Plant","Flowering Plants","Other Flowering Plants","Desmodium nuttallii","Nuttall's Tick Trefoil");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Broome","Animal","Birds","Wood-Warblers","Parkesia motacilla","Louisiana Waterthrush");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Broome","Animal","Birds","Wood-Warblers","Parkesia noveboracensis","Northern Waterthrush");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Broome","Animal","Birds","Wood-Warblers","Seiurus aurocapilla","Ovenbird");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Broome","Animal","Birds","Wood-Warblers","Setophaga americana","Northern Parula");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Broome","Animal","Birds","Wood-Warblers","Setophaga caerulescens","Black-throated Blue Warbler");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cattaraugus","Animal","Birds","Finches and Crossbills","Spinus tristis","American Goldfinch");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cattaraugus","Animal","Birds","Flycatchers","Contopus virens","Eastern Wood-Pewee");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cattaraugus","Animal","Birds","Flycatchers","Empidonax alnorum","Alder Flycatcher");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cattaraugus","Animal","Birds","Flycatchers","Empidonax minimus","Least Flycatcher");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cattaraugus","Animal","Birds","Flycatchers","Empidonax traillii","Willow Flycatcher");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cayuga","Animal","Amphibians","Frogs and Toads","Lithobates sylvaticus","Wood Frog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cayuga","Animal","Amphibians","Frogs and Toads","Pseudacris crucifer","Spring Peeper");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cayuga","Animal","Amphibians","Frogs and Toads","Pseudacris triseriata","Western Chorus Frog");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cayuga","Animal","Amphibians","Salamanders","Ambystoma jeffersonianum","Jefferson Salamander");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Cayuga","Animal","Amphibians","Salamanders","Ambystoma jeffersonianum x laterale","Jefferson Salamander Complex");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chautauqua","Animal","Birds","Loons","Gavia immer","Common Loon");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chautauqua","Animal","Birds","Mockingbirds and Thrashers","Dumetella carolinensis","Gray Catbird");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chautauqua","Animal","Birds","Mockingbirds and Thrashers","Mimus polyglottos","Northern Mockingbird");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chautauqua","Animal","Birds","Mockingbirds and Thrashers","Toxostoma rufum","Brown Thrasher");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chautauqua","Animal","Birds","Nightbirds","Chordeiles minor","Common Nighthawk");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chemung","Animal","Birds","Cardinals and Buntings","Piranga olivacea","Scarlet Tanager");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chemung","Animal","Birds","Chickadees and Titmice","Baeolophus bicolor","Tufted Titmouse");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chemung","Animal","Birds","Chickadees and Titmice","Poecile atricapillus","Black-capped Chickadee");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chemung","Animal","Birds","Creepers","Certhia americana","Brown Creeper");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Chemung","Animal","Birds","Crows and Jays","Corvus brachyrhynchos","American Crow");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Clinton","Animal","Amphibians","Salamanders","Eurycea bislineata","Northern Two-lined Salamander");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Clinton","Animal","Amphibians","Salamanders","Gyrinophilus porphyriticus","Spring Salamander");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Clinton","Animal","Amphibians","Salamanders","Necturus maculosus","Mudpuppy");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Clinton","Animal","Amphibians","Salamanders","Notophthalmus viridescens","Eastern Newt");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Clinton","Animal","Amphibians","Salamanders","Plethodon cinereus","Redback Salamander");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Columbia","Animal","Birds","Hummingbirds and Swifts","Chaetura pelagica","Chimney Swift");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Columbia","Animal","Birds","Kingfishers","Megaceryle alcyon","Belted Kingfisher");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Columbia","Animal","Birds","Kinglets","Regulus satrapa","Golden-crowned Kinglet");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Columbia","Animal","Birds","Mockingbirds and Thrashers","Dumetella carolinensis","Gray Catbird");
insert into species (county,category,taxonomy_g,taxonomy_sg,sci_name,common_name) values("Columbia","Animal","Birds","Mockingbirds and Thrashers","Mimus polyglottos","Northern Mockingbird");
